version: '3.8'

services:

  db: 
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=terraform
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data